// Copyright (c) 2026 Armen Suri
// SPDX-License-Identifier: MIT

// Code generated by scripts/generate_checks.py; DO NOT EDIT.
package registry

import (
	"github.com/learning/governance/soc2/src/pkg/check"
	iam "github.com/learning/governance/soc2/src/iam"
	s3 "github.com/learning/governance/soc2/src/s3"
	ec2 "github.com/learning/governance/soc2/src/ec2"
	rds "github.com/learning/governance/soc2/src/rds"
	cloudtrail "github.com/learning/governance/soc2/src/cloudtrail"
	kms "github.com/learning/governance/soc2/src/kms"
	vpc "github.com/learning/governance/soc2/src/vpc"
	guardduty "github.com/learning/governance/soc2/src/guardduty"
	awsconfig "github.com/learning/governance/soc2/src/awsconfig"
	policies "github.com/learning/governance/soc2/src/policies"
	access "github.com/learning/governance/soc2/src/access"
	risk "github.com/learning/governance/soc2/src/risk"
	hr "github.com/learning/governance/soc2/src/hr"
	monitoring "github.com/learning/governance/soc2/src/monitoring"
	sdlc "github.com/learning/governance/soc2/src/sdlc"
	data "github.com/learning/governance/soc2/src/data"
)

func AllAWS() []check.AWSCheck {
	return []check.AWSCheck{
		iam.NewIAM001MfaEnabledForRootAccount(),
		iam.NewIAM002MfaEnabledForIamUsers(),
		iam.NewIAM003NoUnusedIamCredentials(),
		iam.NewIAM004IamPoliciesLeastPrivilege(),
		iam.NewIAM005NoInlineIamPolicies(),
		iam.NewIAM006IamAccessKeysRotated(),
		s3.NewS3001S3BucketPublicAccessBlocked(),
		s3.NewS3002S3BucketEncryptionEnabled(),
		s3.NewS3003S3BucketVersioningEnabled(),
		s3.NewS3004S3BucketLoggingEnabled(),
		s3.NewS3005S3BucketMfaDeleteEnabled(),
		ec2.NewEC2001NoDefaultVpcUsage(),
		ec2.NewEC2002SecurityGroupsRestrictInbound(),
		ec2.NewEC2003EbsVolumeEncryption(),
		ec2.NewEC2004Ec2InstancesPatched(),
		ec2.NewEC2005Ec2Imdsv2Enforced(),
		rds.NewRDS001RdsEncryptionAtRest(),
		rds.NewRDS002RdsNotPubliclyAccessible(),
		rds.NewRDS003RdsAutomatedBackupsEnabled(),
		rds.NewRDS004RdsMultiAzEnabled(),
		rds.NewRDS005RdsMinorVersionAutoUpgrade(),
		cloudtrail.NewCT001CloudtrailEnabledInAllRegions(),
		cloudtrail.NewCT002CloudtrailLogFileValidation(),
		cloudtrail.NewCT003CloudtrailLogsEncrypted(),
		cloudtrail.NewCT004CloudwatchAlarmsForCloudtrailEvents(),
		kms.NewKMS001KmsKeyRotationEnabled(),
		kms.NewKMS002KmsKeyPoliciesRestrictAccess(),
		vpc.NewVPC001VpcFlowLogsEnabled(),
		vpc.NewVPC002NetworkAclsRestrictTraffic(),
		guardduty.NewGD001GuarddutyEnabled(),
		awsconfig.NewCFG001AwsConfigEnabled(),
	}
}

func AllProcess() []check.ProcessCheck {
	return []check.ProcessCheck{
		policies.NewPOL001InformationSecurityPolicyDocumented(),
		policies.NewPOL002AcceptableUsePolicy(),
		policies.NewPOL003IncidentResponsePlan(),
		policies.NewPOL004ChangeManagementPolicy(),
		policies.NewPOL005BusinessContinuityDisasterRecoveryPlan(),
		access.NewACC001UserAccessReview(),
		access.NewACC002OnboardingOffboardingProcedures(),
		access.NewACC003PrivilegedAccessManagement(),
		access.NewACC004VendorThirdPartyAccessControls(),
		risk.NewRISK001AnnualRiskAssessment(),
		risk.NewRISK002VendorRiskManagement(),
		risk.NewRISK003VulnerabilityManagementProgram(),
		hr.NewHR001BackgroundChecks(),
		hr.NewHR002SecurityAwarenessTraining(),
		hr.NewHR003CodeOfConduct(),
		monitoring.NewMON001CentralizedLogManagement(),
		monitoring.NewMON002SecurityAlertingAndResponse(),
		monitoring.NewMON003LogRetentionPolicy(),
		sdlc.NewSDLC001SecureSdlcPractices(),
		sdlc.NewSDLC002SeparationOfEnvironments(),
		sdlc.NewSDLC003ProductionDeploymentApprovals(),
		data.NewDATA001DataClassificationPolicy(),
		data.NewDATA002DataRetentionAndDisposalPolicy(),
		data.NewDATA003DataEncryptionInTransit(),
		data.NewDATA004PrivacyPolicyAndGdprCcpaCompliance(),
	}
}

func All() []check.AWSCheck {
	return AllAWS()
}
