// Code generated by scripts/generate_checks.py; DO NOT EDIT.
// Copyright (c) 2026 Armen Suri
// SPDX-License-Identifier: MIT
package registry

import (
	"github.com/learning/governance/pci-dss/src/pkg/check"
	access "github.com/learning/governance/pci-dss/src/access"
	authentication "github.com/learning/governance/pci-dss/src/authentication"
	awareness "github.com/learning/governance/pci-dss/src/awareness"
	changemgmt "github.com/learning/governance/pci-dss/src/changemgmt"
	compliance "github.com/learning/governance/pci-dss/src/compliance"
	dataprotect "github.com/learning/governance/pci-dss/src/dataprotect"
	governance "github.com/learning/governance/pci-dss/src/governance"
	guardduty "github.com/learning/governance/pci-dss/src/guardduty"
	incident "github.com/learning/governance/pci-dss/src/incident"
	kmsecrets "github.com/learning/governance/pci-dss/src/kmsecrets"
	logging "github.com/learning/governance/pci-dss/src/logging"
	malware "github.com/learning/governance/pci-dss/src/malware"
	network "github.com/learning/governance/pci-dss/src/network"
	physical "github.com/learning/governance/pci-dss/src/physical"
	risk "github.com/learning/governance/pci-dss/src/risk"
	secureconfig "github.com/learning/governance/pci-dss/src/secureconfig"
	securedev "github.com/learning/governance/pci-dss/src/securedev"
	securityhub "github.com/learning/governance/pci-dss/src/securityhub"
	transmission "github.com/learning/governance/pci-dss/src/transmission"
	vulntest "github.com/learning/governance/pci-dss/src/vulntest"
)

func AllAWS() []check.AWSCheck {
	return []check.AWSCheck{
		network.NewNET001CdeIsolatedInDedicatedVpc(),
		network.NewNET002SecurityGroupsRestrictInboundToCde(),
		network.NewNET003SecurityGroupsDenyAllByDefault(),
		network.NewNET004VpcFlowLogsEnabled(),
		network.NewNET005CdeResourcesInPrivateSubnets(),
		network.NewNET006WafEnabledOnPublicFacingApplications(),
		network.NewNET007NetworkAclsRestrictCdeTraffic(),
		network.NewNET008NoDirectInternetAccessToCde(),
		secureconfig.NewCFG001NoDefaultCredentialsOnCdeSystems(),
		secureconfig.NewCFG002CdeSystemsHardenedPerBaseline(),
		secureconfig.NewCFG003UnnecessaryServicesDisabledOnCdeSystems(),
		secureconfig.NewCFG004AwsConfigEnabledForCdeAccounts(),
		secureconfig.NewCFG005Ec2Imdsv2Enforced(),
		dataprotect.NewDATA001NoStorageOfSensitiveAuthenticationDataPostAuthorization(),
		dataprotect.NewDATA002PanMaskedWhenDisplayed(),
		dataprotect.NewDATA003PanEncryptedAtRestWithStrongCryptography(),
		dataprotect.NewDATA004S3EncryptionEnabledForCdeBuckets(),
		dataprotect.NewDATA005EbsEncryptionEnabledForCdeInstances(),
		dataprotect.NewDATA006RdsEncryptionEnabledForCdeDatabases(),
		dataprotect.NewDATA007KeyManagementPolicyForEncryptionKeys(),
		dataprotect.NewDATA008CardholderDataDiscoveryScan(),
		dataprotect.NewDATA009AmazonMacieEnabledForCdeS3Buckets(),
		transmission.NewTLS001Tls12EnforcedOnAllCdeEndpoints(),
		transmission.NewTLS002S3BucketsEnforceSslOnlyAccess(),
		transmission.NewTLS003StrongCipherSuitesEnforced(),
		transmission.NewTLS004NoCardholderDataSentViaUnencryptedChannels(),
		malware.NewMAL001AntiMalwareSolutionOnCdeSystems(),
		malware.NewMAL002GuarddutyMalwareProtectionEnabled(),
		malware.NewMAL003AntiMalwareDefinitionsKeptCurrent(),
		malware.NewMAL004Ec2InstancesRegularlyPatched(),
		securedev.NewDEV001CriticalVulnerabilitiesPatchedPromptly(),
		securedev.NewDEV002AwsInspectorEnabledForCdeAccounts(),
		securedev.NewDEV003WafActiveAndTunedForCdeApplications(),
		securedev.NewDEV004SastDastInCiCdPipeline(),
		securedev.NewDEV005SeparationOfCdeEnvironments(),
		securedev.NewDEV006NoLivePansInTestEnvironments(),
		access.NewACC001IamLeastPrivilegeForCdeResources(),
		access.NewACC002NoSharedIamCredentialsForCde(),
		access.NewACC003RoleBasedAccessControlForCde(),
		access.NewACC004QuarterlyAccessReviewsForCde(),
		access.NewACC005S3CdeBucketsBlockPublicAccess(),
		access.NewACC006RdsNotPubliclyAccessible(),
		authentication.NewAUTH001MfaRequiredForAllCdeAccess(),
		authentication.NewAUTH002MfaOnRootAccount(),
		authentication.NewAUTH003IamPasswordPolicyEnforced(),
		authentication.NewAUTH004IamAccessKeysRotatedEvery90Days(),
		authentication.NewAUTH005NoUnusedIamCredentials(),
		authentication.NewAUTH006AutomaticSessionTimeoutConfigured(),
		authentication.NewAUTH007ServiceAccountCredentialsManagedSecurely(),
		logging.NewLOG001CloudtrailEnabledInAllCdeRegions(),
		logging.NewLOG002CloudtrailLogFileIntegrityValidation(),
		logging.NewLOG003CloudtrailLogsEncryptedWithKms(),
		logging.NewLOG004S3DataEventsLoggedForCdeBuckets(),
		logging.NewLOG005LogRetentionMinimum12Months(),
		logging.NewLOG006CentralizedLogManagementSiem(),
		logging.NewLOG007AlertsForCriticalSecurityEvents(),
		logging.NewLOG008AuditLogAccessRestricted(),
		logging.NewLOG009S3ObjectLockOnLogBuckets(),
		vulntest.NewTEST001QuarterlyVulnerabilityScansAsv(),
		vulntest.NewTEST002AnnualPenetrationTestOfCde(),
		vulntest.NewTEST003InternalVulnerabilityScansQuarterly(),
		vulntest.NewTEST004SegmentationTestingEvery6Months(),
		vulntest.NewTEST005IdsIpsOnCdeNetwork(),
		vulntest.NewTEST006FileIntegrityMonitoringFimOnCdeSystems(),
		kmsecrets.NewKMS001KmsCmkUsedForCdeEncryption(),
		kmsecrets.NewKMS002KmsKeyRotationEnabled(),
		kmsecrets.NewKMS003SecretsManagerForAllCdeCredentials(),
		guardduty.NewGD001GuarddutyEnabledInAllCdeRegions(),
		securityhub.NewSH001AwsSecurityHubPciDssStandardEnabled(),
	}
}

func AllProcess() []check.ProcessCheck {
	return []check.ProcessCheck{
		governance.NewGOV001InformationSecurityPolicyDocumentedAndReviewedAnnually(),
		governance.NewGOV002PciDssScopeDefinedAndDocumented(),
		governance.NewGOV003AnnualPciDssScopeReview(),
		governance.NewGOV004PciDssResponsibilityMatrixDefined(),
		risk.NewRISK001AnnualFormalRiskAssessment(),
		risk.NewRISK002ThirdPartyVendorRiskManagement(),
		risk.NewRISK003ServiceProviderListMaintained(),
		incident.NewIR001IncidentResponsePlanForCde(),
		incident.NewIR002IrpTestedAnnually(),
		incident.NewIR003247IncidentResponseCapability(),
		incident.NewIR004BreachNotificationProcedures(),
		awareness.NewSAT001AnnualPciDssSecurityAwarenessTraining(),
		awareness.NewSAT002SocialEngineeringPhishingTraining(),
		awareness.NewSAT003AcceptableUsePolicyAcknowledgment(),
		changemgmt.NewCHG001FormalChangeManagementProcessForCde(),
		changemgmt.NewCHG002SecurityImpactAssessmentForCdeChanges(),
		changemgmt.NewCHG003ProductionDeploymentApprovals(),
		physical.NewPHY001PhysicalAccessToCdeSystemsRestricted(),
		physical.NewPHY002VisitorManagementProcedures(),
		physical.NewPHY003MediaContainingCardholderDataSecured(),
		physical.NewPHY004SecureDestructionOfMediaWithCardholderData(),
		physical.NewPHY005AwsDataCenterPhysicalSecurity(),
		compliance.NewCOMP001AnnualPciDssAssessmentQsaOrSaq(),
		compliance.NewCOMP002CompensatingControlsDocumented(),
		compliance.NewCOMP003ExecutiveResponsibilityForPciDssCompliance(),
	}
}
